### ISSUE TITLE
Is there any plans on supporting the Circle Hough Transform (CHT)

### ISSUE THREAD

**Issue by peterhellberg** [fwessels/go-cv#1]
I recently used the [Hough Circle Transform](http://docs.opencv.org/2.4/doc/tutorials/imgproc/imgtrans/hough_circle/hough_circle.html) in OpenCV, but found the combination of Python and OpenCV to be quite unpleasant to work with (but effective). I'd prefer to use pure Go :)

Do you have any plans of supporting (fairly high level) feature detection algorithms like this in go-cv?

# Links
 - https://en.wikipedia.org/wiki/Circle_Hough_Transform
 - https://imagej.net/Hough_Circle_Transform

**Comment by fwessels** [comment]
If we get the time to get around it, then yes maybe, but not anytime soon though.
